version: '3.8'

services:
  api01: &api
    image: rogerfelipensk/rinha-q1-2024-hyper-express-pg:latest
    hostname: api01
    networks:
      - rinha-backend
    environment:
      - DB_HOSTNAME=db
      - PORT=5000
    ports:
      - '5001:5000'
    depends_on:
      - db
    deploy:
      resources:
        limits:
          cpus: '0.25'
          memory: '100MB'
  api02:
    <<: *api
    hostname: api02
    environment:
      - DB_HOSTNAME=db
      - PORT=5000
    ports:
      - '5002:5000'

  nginx:
    image: nginx:latest
    networks:
      - rinha-backend
    volumes:
      - ./DockerScripts/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./DockerScripts/ssl:/etc/nginx/ssl:ro
    depends_on:
      - api01
      - api02
    ports:
      # Obrigatório expor/usar a porta 9999 no load balancer!
      - '9999:9999'
    deploy:
      resources:
        limits:
          cpus: '0.1'
          memory: '30MB'

  db:
    image: postgres:latest
    hostname: db
    environment:
      - POSTGRES_PASSWORD=123
      - POSTGRES_USER=admin
      - POSTGRES_DB=rinha
    ports:
      - '5432:5432'
    volumes:
      - ./DockerScripts/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./DockerScripts/postgresql.conf:/docker-entrypoint-initdb.d/postgresql.conf
    networks:
      - rinha-backend
    deploy:
      resources:
        limits:
          cpus: '0.9'
          memory: '300MB'

networks:
  rinha-backend:
    driver: bridge
